# -*- coding: utf-8 -*-
"""
/***************************************************************************
 testPlugin
                                 A QGIS plugin
 wadawd
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-03-31
        copyright            : (C) 2024 by awd
        email                : awfwafd@adawd.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'awd'
__date__ = '2024-03-31'
__copyright__ = '(C) 2024 by awd'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load testPlugin class from file testPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .testPluginModule import testPluginPlugin
    return testPluginPlugin()
